name: test
on:
    [workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: npm clean-install
            - run: npm ci
            - uses: ./
            - uses: ./
              with:
                person: 'batman'
            - run: echo "hello srini"
